CREATE TABLE IF NOT EXISTS after_sale_case (
  case_id BIGINT PRIMARY KEY AUTO_INCREMENT,
  order_id BIGINT NOT NULL,
  task_id BIGINT NULL,
  user_id BIGINT NOT NULL,
  buyer_id BIGINT NULL,
  case_type VARCHAR(40) NOT NULL,
  case_status VARCHAR(40) NOT NULL,
  issue_reason VARCHAR(255) NOT NULL,
  evidence_url VARCHAR(255) NULL,
  replacement_sku_name VARCHAR(120) NULL,
  suggested_refund_amount DECIMAL(10,2) NULL,
  negotiated_refund_amount DECIMAL(10,2) NULL,
  user_decision VARCHAR(40) NULL,
  user_comment VARCHAR(255) NULL,
  arbitration_result VARCHAR(60) NULL,
  risk_level VARCHAR(20) NOT NULL,
  origin_order_status VARCHAR(40) NOT NULL,
  admin_id BIGINT NULL,
  arbitration_comment VARCHAR(255) NULL,
  user_decision_at DATETIME NULL,
  arbitrated_at DATETIME NULL,
  closed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_after_sale_case_order FOREIGN KEY (order_id) REFERENCES order_main(order_id),
  CONSTRAINT fk_after_sale_case_task FOREIGN KEY (task_id) REFERENCES procurement_task(task_id),
  INDEX idx_after_sale_order_status (order_id, case_status, created_at),
  INDEX idx_after_sale_type_status (case_type, case_status, created_at),
  INDEX idx_after_sale_risk_status (risk_level, case_status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
