server:
  port: 8080

spring:
  application:
    name: hk-buyer-backend
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hk_buyer?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: hk_buyer
    password: hk_buyer
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
      write-dates-as-timestamps: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
